name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        token: ${{ secrets.PAT_TOKEN }}
        persist-credentials: false
    - name: Bump version and push tag
      id: set_version
      uses: anothrNick/github-tag-action@1.17.2
      with:
        token: ${{ secrets.PAT_TOKEN }}
      env:
        WITH_V: true
        DRY_RUN: true
    - name: Push version tag
      run: |
        git config --local user.email "tarcisio.genaro@gmail.com"
        git config --local user.name "tarc"
        git tag ${{steps.set_version.outputs.new_tag}}
        git push "https://tarc:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master --tags

    - name: Echo new_tag
      run: |
        echo new_tag: ${{steps.set_version.outputs.new_tag}}
