name: Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: pipenv install --dev

      - name: Test with pytest
        run: pipenv run python -m unittest -v
