name: Test and Coverage

on:
  push:
    branches: [ master, develop, feature/* ]

jobs:
  build:
    name: Test and Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run tests and coverage
        run: pipenv run coverage run --source=asyncfileserver setup.py test
      - name: Publish coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: pipenv run coveralls
