name: Test

on:
  push:
    branches: [ master, develop, feature/* ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: pipenv install --dev

      - name: Test with pytest
        run: pipenv run python -m unittest -v
