name: Test

on:
  push:
    branches: [ feature/*, hotfix/* ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run tests and coverage
        run: pipenv run coverage run --source asyncfileserver setup.py test
      - name: Create XML report of coverage results
        run: pipenv run coverage xml
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: asyncfileserver
          fail_ci_if_error: true
